/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aguatzi.sistemaAguatzi.vista;

/**
 *
 * @author Omar Guerrero
 */
public class FrmCierreCajaLocal extends javax.swing.JFrame {

    /**
     * Creates new form FrmCierreCajaLocal
     */
    public FrmCierreCajaLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLecturaMedidor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblGarrafonesRuta = new javax.swing.JLabel();
        lblGarrafonesNuevos = new javax.swing.JLabel();
        lblPagadosTranasferencia = new javax.swing.JLabel();
        lblGarrafonesVaciados = new javax.swing.JLabel();
        lblDineroVenta = new javax.swing.JLabel();
        lblGarrafonesVendidos = new javax.swing.JLabel();
        lblLitrosVendidos = new javax.swing.JLabel();
        lblDineroCaja = new javax.swing.JLabel();
        lblFaltante = new javax.swing.JLabel();
        txtLecturaMedidor = new javax.swing.JTextField();
        txtLecturaMedidor1 = new javax.swing.JTextField();
        txtLecturaMedidor2 = new javax.swing.JTextField();
        txtLecturaMedidor3 = new javax.swing.JTextField();
        txtLecturaMedidor4 = new javax.swing.JTextField();
        txtLecturaMedidor5 = new javax.swing.JTextField();
        txtLecturaMedidor6 = new javax.swing.JTextField();
        txtLecturaMedidor7 = new javax.swing.JTextField();
        txtLecturaMedidor8 = new javax.swing.JTextField();
        txtLecturaMedidor9 = new javax.swing.JTextField();
        txtLecturaMedidor10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(58, 138, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLecturaMedidor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLecturaMedidor.setForeground(new java.awt.Color(255, 255, 255));
        lblLecturaMedidor.setText("Lectura Medidor");
        jPanel1.add(lblLecturaMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lectura Anterior");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        lblGarrafonesRuta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGarrafonesRuta.setForeground(new java.awt.Color(255, 255, 255));
        lblGarrafonesRuta.setText("Garrafones Para Ruta");
        jPanel1.add(lblGarrafonesRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        lblGarrafonesNuevos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGarrafonesNuevos.setForeground(new java.awt.Color(255, 255, 255));
        lblGarrafonesNuevos.setText("Garrafones Nuevos");
        jPanel1.add(lblGarrafonesNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        lblPagadosTranasferencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPagadosTranasferencia.setForeground(new java.awt.Color(255, 255, 255));
        lblPagadosTranasferencia.setText("Pagados Por Trasferencia");
        jPanel1.add(lblPagadosTranasferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        lblGarrafonesVaciados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGarrafonesVaciados.setForeground(new java.awt.Color(255, 255, 255));
        lblGarrafonesVaciados.setText("Garrafones Vaciados");
        jPanel1.add(lblGarrafonesVaciados, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        lblDineroVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDineroVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroVenta.setText("Dinero Venta Total");
        jPanel1.add(lblDineroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        lblGarrafonesVendidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGarrafonesVendidos.setForeground(new java.awt.Color(255, 255, 255));
        lblGarrafonesVendidos.setText("Garrafones Vendidos");
        jPanel1.add(lblGarrafonesVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        lblLitrosVendidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLitrosVendidos.setForeground(new java.awt.Color(255, 255, 255));
        lblLitrosVendidos.setText("Litros Vendidos");
        jPanel1.add(lblLitrosVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        lblDineroCaja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDineroCaja.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroCaja.setText("Dinero En Caja");
        jPanel1.add(lblDineroCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        lblFaltante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFaltante.setForeground(new java.awt.Color(255, 255, 255));
        lblFaltante.setText("Faltante");
        jPanel1.add(lblFaltante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));
        jPanel1.add(txtLecturaMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 141, -1));
        jPanel1.add(txtLecturaMedidor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 141, -1));
        jPanel1.add(txtLecturaMedidor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 141, -1));
        jPanel1.add(txtLecturaMedidor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 141, -1));
        jPanel1.add(txtLecturaMedidor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 141, -1));
        jPanel1.add(txtLecturaMedidor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 141, -1));
        jPanel1.add(txtLecturaMedidor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 141, -1));
        jPanel1.add(txtLecturaMedidor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 141, -1));
        jPanel1.add(txtLecturaMedidor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 141, -1));
        jPanel1.add(txtLecturaMedidor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 141, -1));
        jPanel1.add(txtLecturaMedidor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 141, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCierreCajaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCierreCajaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCierreCajaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCierreCajaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCierreCajaLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDineroCaja;
    private javax.swing.JLabel lblDineroVenta;
    private javax.swing.JLabel lblFaltante;
    private javax.swing.JLabel lblGarrafonesNuevos;
    private javax.swing.JLabel lblGarrafonesRuta;
    private javax.swing.JLabel lblGarrafonesVaciados;
    private javax.swing.JLabel lblGarrafonesVendidos;
    private javax.swing.JLabel lblLecturaMedidor;
    private javax.swing.JLabel lblLitrosVendidos;
    private javax.swing.JLabel lblPagadosTranasferencia;
    private javax.swing.JTextField txtLecturaMedidor;
    private javax.swing.JTextField txtLecturaMedidor1;
    private javax.swing.JTextField txtLecturaMedidor10;
    private javax.swing.JTextField txtLecturaMedidor2;
    private javax.swing.JTextField txtLecturaMedidor3;
    private javax.swing.JTextField txtLecturaMedidor4;
    private javax.swing.JTextField txtLecturaMedidor5;
    private javax.swing.JTextField txtLecturaMedidor6;
    private javax.swing.JTextField txtLecturaMedidor7;
    private javax.swing.JTextField txtLecturaMedidor8;
    private javax.swing.JTextField txtLecturaMedidor9;
    // End of variables declaration//GEN-END:variables
}
